name: CI garagephp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
     - name: Checkout du code
       uses: actions/checkout@v4

     - name: Config PHP
       uses: shivammathur/setup-php@v2
       with:
       php-version: '8.2' #version de php de xampp
       extensions: pdo_mysql, mbstring #ajoute les extensions nécéssaires
       tools: composer #install composer

     - name: Instalations dependances composer
       run: composer install --no-interaction --prefer-dist --optimize-autoloader

     - name: Execution des tests phpUnit
       run: vendor/bin/phpunit #assurer vous que phpUnit est configuré
