name: CI garagephp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Config PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Indentation correcte pour les options sous 'with'
          extensions: pdo_mysql, mbstring
          tools: composer

      - name: Installation des dépendances composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Exécution des tests phpUnit
        run: vendor/bin/phpunit
